<?php

namespace App\Services;

use App\Models\Service;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ServiceService
{
    /**
     * Create a new service.
     *
     * @param array $data
     * @return Service
     */
    public function createService(array $data): Service
    {
        // Handle image upload if present
        if (isset($data['image']) && $data['image'] instanceof UploadedFile) {
            $data['image_url'] = $this->uploadImage($data['image']);
            unset($data['image']);
        }

        // Service ID will be auto-generated by model if not provided
        return Service::create($data);
    }

    /**
     * Update a service.
     *
     * @param Service $service
     * @param array $data
     * @return Service
     */
    public function updateService(Service $service, array $data): Service
    {
        // Handle image upload if present
        if (isset($data['image']) && $data['image'] instanceof UploadedFile) {
            // Delete old image if exists
            if ($service->image_url) {
                $this->deleteImage($service->image_url);
            }
            $data['image_url'] = $this->uploadImage($data['image']);
            unset($data['image']);
        }

        $service->update($data);
        return $service->fresh();
    }

    /**
     * Delete a service (soft delete).
     *
     * @param Service $service
     * @return bool
     */
    public function deleteService(Service $service): bool
    {
        // Optionally delete image file
        // if ($service->image_url) {
        //     $this->deleteImage($service->image_url);
        // }

        return $service->delete();
    }

    /**
     * Upload service image.
     *
     * @param UploadedFile $file
     * @return string
     */
    public function uploadImage(UploadedFile $file): string
    {
        $filename = time() . '_' . Str::random(10) . '.' . $file->getClientOriginalExtension();
        $path = $file->storeAs('services', $filename, 'public');

        return $filename; // Return just the filename, full URL handled by model accessor
    }

    /**
     * Delete service image.
     *
     * @param string $imageUrl
     * @return bool
     */
    public function deleteImage(string $imageUrl): bool
    {
        // If it's a full URL, extract filename
        if (filter_var($imageUrl, FILTER_VALIDATE_URL)) {
            $imageUrl = basename($imageUrl);
        }

        return Storage::disk('public')->delete('services/' . $imageUrl);
    }

    /**
     * Search services with filters.
     *
     * @param array $filters
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function searchServices(array $filters = [])
    {
        $query = Service::query();

        // Apply category filter
        if (isset($filters['category'])) {
            $query->byCategory($filters['category']);
        }

        // Apply status filter
        if (isset($filters['status'])) {
            $query->byStatus($filters['status']);
        }

        // Apply search term
        if (isset($filters['search']) && !empty($filters['search'])) {
            $query->search($filters['search']);
        }

        // Apply sorting
        $sortBy = $filters['sort'] ?? 'created_at';
        $order = $filters['order'] ?? 'desc';

        if (in_array($sortBy, ['name', 'created_at', 'active_clients'])) {
            $query->orderBy($sortBy, $order);
        } else {
            $query->orderBy('created_at', 'desc');
        }

        return $query;
    }

    /**
     * Update active clients count.
     *
     * @param Service $service
     * @param int $count
     * @return Service
     */
    public function updateActiveClients(Service $service, int $count): Service
    {
        $service->update(['active_clients' => max(0, $count)]);
        return $service->fresh();
    }

    /**
     * Increment active clients.
     *
     * @param Service $service
     * @param int $amount
     * @return Service
     */
    public function incrementActiveClients(Service $service, int $amount = 1): Service
    {
        $service->incrementActiveClients($amount);
        return $service->fresh();
    }

    /**
     * Decrement active clients.
     *
     * @param Service $service
     * @param int $amount
     * @return Service
     */
    public function decrementActiveClients(Service $service, int $amount = 1): Service
    {
        $service->decrementActiveClients($amount);
        return $service->fresh();
    }

    /**
     * Get services by category.
     *
     * @param string $category
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getServicesByCategory(string $category)
    {
        return Service::byCategory($category)->active()->get();
    }

    /**
     * Get active services.
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getActiveServices()
    {
        return Service::active()->get();
    }

    /**
     * Generate next service ID.
     *
     * @return string
     */
    public function generateNextServiceId(): string
    {
        return Service::generateServiceId();
    }
}

